# Generated by Django 5.0.2 on 2024-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
