# Generated by Django 5.0.2 on 2024-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0006_contact_git_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='work',
            name='git_hub',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='work',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
